# Generated by Django 6.0.5 on 2026-06-01 04:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit', 'Credit'), ('investment', 'Investment')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_frozen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fintech_account',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(db_index=True, max_length=16, unique=True)),
                ('card_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('prepaid', 'Prepaid')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('cvv_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('expired', 'Expired'), ('lost', 'Lost/Stolen')], default='active', max_length=20)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='fintech.account')),
            ],
            options={
                'db_table': 'fintech_card',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fintech_merchant',
                'indexes': [models.Index(fields=['category'], name='fintech_mer_categor_33574a_idx'), models.Index(fields=['country'], name='fintech_mer_country_a2567f_idx'), models.Index(fields=['name', 'category'], name='fintech_mer_name_3a3d32_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('transfer', 'Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fintech.account')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fintech.card')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fintech.merchant')),
            ],
            options={
                'db_table': 'fintech_transaction',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credit_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
            ],
            options={
                'db_table': 'fintech_user',
                'indexes': [models.Index(fields=['email'], name='fintech_use_email_1419f4_idx'), models.Index(fields=['phone'], name='fintech_use_phone_893edb_idx'), models.Index(fields=['-date_joined'], name='fintech_use_date_jo_842f48_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('credit_score__gte', 300), ('credit_score__isnull', True), _connector='OR'), name='credit_score_min_300'), models.CheckConstraint(condition=models.Q(('credit_score__lte', 850), ('credit_score__isnull', True), _connector='OR'), name='credit_score_max_850')],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='fintech.user'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['card_number'], name='fintech_car_card_nu_c19f57_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['account', 'status'], name='fintech_car_account_4bbdbd_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['expiry_date'], name='fintech_car_expiry__2bf39e_idx'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('daily_limit__gte', 0)), name='daily_limit_positive'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='fintech_tra_transac_a47b44_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-created_at'], name='fintech_tra_account_007959_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='fintech_tra_status_e3866a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['merchant', 'status'], name='fintech_tra_merchan_c2e39f_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('merchant__isnull', True), ('transaction_type', 'deposit')), models.Q(('merchant__isnull', True), ('transaction_type', 'withdrawal')), models.Q(('merchant__isnull', False), ('transaction_type', 'purchase')), models.Q(('merchant__isnull', True), ('transaction_type', 'transfer')), _connector='OR'), name='valid_merchant_for_transaction_type'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_number'], name='fintech_acc_account_bff643_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'account_type'], name='fintech_acc_user_id_9943b9_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['-balance'], name='fintech_acc_balance_366910_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type', 'checking')), fields=('user', 'account_type'), name='unique_checking_per_user'),
        ),
    ]
